### ISSUE TITLE
version 1.10.2 not working

### ISSUE THREAD

**Issue by Jay9519** [maruohon/environmentalcreepers#1]
Environmental Creepers  1.10.2  1.1.0
Sponge 1.10.2-2281-5.2.0-BETA-2341
Forge 12.18.3.2297

option to turn creepers destroying blocks turned off in the config but it's not working

**Comment by maruohon** [comment]
Works fine for me on just Forge (2281).

* Did you (re-)start the server after modifying the config?
* Did you try without Sponge, maybe it changes something?

**Comment by Jay9519** [comment]
yes I did restart the server after I changed the settings

# Configuration file

generic {
    # The chance of Creeper explosions to drop the blocks as items. Set to 1.0 to always drop.
    D:creeperExplosionBlockDropChance=1.0

    # The strength of Charged Creeper explosions. Default in vanilla: 6.0 (double of normal Creepers).
    D:creeperExplosionStrengthCharged=0.0

    # The strength of Creeper explosions. Default in vanilla: 3.0 for normal Creepers (becomes double ie. 6.0 for Charged Creepers).
    D:creeperExplosionStrengthNormal=1.0

    # Completely disable Creeper explosion from damaging blocks
    B:disableCreeperExplosionBlockDamage=true

    # Disable Creeper explosions from damaging items on the ground
    B:disableCreeperExplosionItemDamage=true

    # Completely disable other explosions than Creepers from damaging blocks
    B:disableOtherExplosionBlockDamage=true

    # Disable other explosions than Creepers from damaging items on the ground
    B:disableOtherExplosionItemDamage=true

    # Modify the chance of Creeper explosions to drop the blocks as items. Set the chance in creeperExplosionBlockDropChance.
    B:modifyCreeperExplosionDropChance=true

    # Modify the strength of Creeper explosions.
    B:modifyCreeperExplosionStrength=true

    # Modify the chance of other explosions than Creepers to drop the blocks as items. Set the chance in otherExplosionBlockDropChance.
    B:modifyOtherExplosionDropChance=true

    # The chance of other explosions than Creepers to drop the blocks as items. Set to 1.0 to always drop.
    D:otherExplosionBlockDropChance=1.0
}

I can't run my modded server without Sponge installed

**Comment by maruohon** [comment]
I looked into it more and added some debug logging. It seems that the way Sponge replaces the explosion, it won't even fire the Forge events. So there is nothing I can do from a Forge mod to make this work on Sponge.

It would have to be a Sponge plugin that uses the Sponge API and disables the explosion block damage. Unless Sponge would consider not firing the Forge events a bug, and change how their explosion code works...

**Comment by Jay9519** [comment]
Thanks heaps for looking into this for me, I will continue my search for a sponge compatible mod :)

**Comment by DragonEggBedrockBreaking** [comment]
Please close this issue.
