### ISSUE TITLE
Creeper explosions cause server crashes on 1.16.3

### ISSUE THREAD

**Issue by LessThanBenji** [maruohon/environmentalcreepers#10]
Hi, amazing mod, I'm just having an issue with it at the moment though. I'm using Environmental Creepers v1.6.0 for Fabric on the latest 1.16.3 build of Fabric, I have the config file set entirely to default besides 3 options (disabled modifying the drop chance, enabled modifying the explosion strength, and set that modified explosion strength for normal creepers to 2.0), and whenever a Creeper explodes my dedicated server instantaneously crashes. I was running EC alongside Lithium, Phosphor, Carpet (with the minitweaks addon), and the Fabric API (latest release) obviously, but I did plop EC into a new directory on its own to double check it wasn't another mod causing the issue and the same crash happened. I was gonna upload my logs but it's such an easy crash to recreate, just modify the explosion strength and get a Creeper to detonate. Could it be because I'm running it on 1.16.3 and it only works on .4? The file is marked .3 as well as .2 and .4 so I thought it would work fine. Any help would be great, and of course I can upload a crash report / log / config file if you need. Thanks so much!

**Comment by maruohon** [comment]
That crash is a really weird one, it shouldn't be happening but obviously it is...

I now uploaded version `1.16.4-1.6.1` which fixes this crash.

**Comment by LessThanBenji** [comment]
you're amazing thank you so much!
