### ISSUE TITLE
AE Singularities

### ISSUE THREAD

**Issue by ZeekDaGeek** [maruohon/environmentalcreepers#4]
In order to create Quantum Entangled Singularities (https://ae-mod.info/Quantum-Entangled-Singularity/) you need to use an explosion on a Singularity + Ender Dust, however, with explosion item protection on it becomes impossible to create one. Would it be possible to add a special rule to allow these explosion based crafting operations to work?

**Comment by maruohon** [comment]
I don't think there is any generic way to recognize crafting recipe use cases. I think the best option would be to just add a blacklist for entities or even specific items contained in vanilla `EntityItem`s to exclude from the explosion protection. It looks like AE2 has their own entity for the singularity, meaning that the entity blacklist should work.

**Comment by maruohon** [comment]
I uploaded version 1.5.0, which blacklists the AE2 Singularities by default. It seemed to work in my testing, but let me know if there are some issues.

**Comment by ZeekDaGeek** [comment]
Thank you, looks like it works perfectly out of the box.
