### ISSUE TITLE
Litematica can''t read block pallerr

### ISSUE THREAD

**Issue by MrDDog** [maruohon/environmentalcreepers#5]
I insalled litematica and it runs really well however i found this build i want to do but whenever i select it it says that it can't read the block pallett how do i fix that

**Comment by maruohon** [comment]
Why did you post this in the Environmental Creepers mod's repo?

As for the issue, which Minecraft version are you on? For 1.14.4 I uploaded a new build yesterday at: https://pena2.dy.fi/tmp/minecraft/mods/client_mods/ which should mostly support all non-Sponge-format `*.schematic` files.

**Comment by MrDDog** [comment]
Sorry i only installed gift hub to msg you this and don't understand it

**Comment by MrDDog** [comment]
Thx

**Comment by maruohon** [comment]
So did you try that new version and did it work?

**Comment by MrDDog** [comment]
Yh thx
