### ISSUE TITLE
Crash on Server 1.15.1

### ISSUE THREAD

**Issue by jrjespersen** [maruohon/environmentalcreepers#7]
I get a crash when trying to add this mod to MineCraft 1.15.1 server.

Crash: https://pastebin.com/VvhyGAq8
Minecraft Version: 1.15.1
Forge Version: forge-1.15.1-30.0.51
No other mods loaded.

**Comment by maruohon** [comment]
I uploaded a new version **1.6.1**, which fixes the crash introduced by the Forge build `30.0.51` specifically. You can use that **1.6.1** version on both that latest Forge 1.15.1 build `30.0.51`, and the 1.15.2 Forge versions.

**Comment by jrjespersen** [comment]
Thanks, will try it out tonight!
