### ISSUE TITLE
[1.16.1-Forge] Crash when entering world.

### ISSUE THREAD

**Issue by Gbergz** [maruohon/environmentalcreepers#8]
Title^
Game crashes when entering an existing or creating a world. Mod was working fine before the .67 update of Forge. After that many mods had problems.

**Forge:** 32.0.70
**MC:** 1.16.1
**Mod Version:** 1.6.0

**Crash-Report:**
https://hastebin.com/qatasobiwi.rb

**Comment by maruohon** [comment]
Yeah they changed how commands are registered in 32.0.67, so I assume pretty much all mods that have commands would crash in 67+ using the older mod builds...

**Comment by maruohon** [comment]
This was fixed in version 1.6.1 for MC 1.16.1.
